language: python

os:
  - linux

git:
  depth: 1

apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
python:
  - "3.5"
  - "3.6"
install:
  - sudo python setup.py install 
script:
  - cd partypi && sudo python main.py 
