language: python
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
python:
  - "3.5"
  - "3.6"
install:
  - python setup.py install 
script:
  - cd partypi && python main.py 
